# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .provider import *
from .self_signed_certificate import *
_utilities.register(
    resource_modules="""
[
 {
  "pkg": "banana",
  "mod": "index",
  "fqn": "pulumi_banana",
  "classes": {
   "banana:index:SelfSignedCertificate": "SelfSignedCertificate"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "banana",
  "token": "pulumi:providers:banana",
  "fqn": "pulumi_banana",
  "class": "Provider"
 }
]
"""
)
